### PR TITLE
Fixing boundary detection using stream headers

### PR DESCRIPTION
**Pull request by hughreeling**
When the connection to the stream is established, the headers contain 'Content-type' and this contains a 'boundary' string that identified the string used to delimit images in the stream.
This change extracts this string, and uses is in the regex to identify the frame breaks.

### CODE REVIEW

**Comment by hughreeling** [comment]
One other thought - didn't put too much care into the error handling - just threw exceptions - perhaps we need to do more there.

**Comment by perthcpe23** [comment]
How about falling back to default Regex like the one we've been using?

```java
Pattern pattern = Pattern.compile("--[_a-zA-Z0-9]*boundary\\s+(.*)\\r\\n\\r\\n",Pattern.DOTALL);
```

**Comment by hughreeling** [comment]
Good idea.  I'll update tonight.

**Comment by perthcpe23** [comment]
I made a change about falling back to a default pattern. Could you please check if you satisfy with that, if not, feel free make any change you would like. Then, I can merge all these changes and release a new version.

**Comment by perthcpe23** [comment]
I made a change about falling back to a default pattern. Could you please check if you satisfy with that, if not, feel free make any change you would like. Then, I can merge all these changes and release a new version. (Sorry, accidentally close the issue, re-opened)

**Pull request merged**
